#!/bin/sh
set -e

echo '+cargo clippy --all --all-targets --all-features -- -D warnings'
cargo clippy --all --all-targets --all-features -- -D warnings
echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check
